version: "3.9"
services:
  php:
    image: php:fpm-alpine3.15
    container_name: php
    volumes:
     - ./website/:/var/www/html/
    networks:
      - mynetwork
    restart: always
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./website/:/var/www/html/
      - ./cert.crt:/etc/nginx/cert.crt
      - ./cert.key:/etc/nginx/cert.key
    networks:
      - mynetwork
    restart: always
    ports:
      - "80:80"
      - "443:443"
networks:
  mynetwork:
